# Generated by Django 3.2.4 on 2021-07-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageLoader', '0002_auto_20210630_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.IntegerField(default=None),
        ),
    ]
