# Generated by Django 3.2.4 on 2021-07-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageLoader', '0005_auto_20210701_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
